// <auto-generated />
namespace ProductAlert.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class kjo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(kjo));
        
        string IMigrationMetadata.Id
        {
            get { return "202212120938356_kjo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
